### ISSUE TITLE
Better Model

### ISSUE THREAD

**Issue by Krish2208** [VishalSinghParmar2001/Relating-Social-Media-to-Stock-Movement-Public#3]
I am GSSoC 22 Participant. I would like to suggest some changes and work on them:-

- Implementing GridSearchCV for better tuning and increasing prediction metric scores.
- Implementing a Pipeline for better management and streamlining the workflow.
- Try to implement other algorithms like SVC and KNN models to check for better prediction and comparison.

I would also like to work on these suggestions.
Please assign these issues to me.

**Comment by Himanshu1808** [comment]
I would like to work on this issue, can you please assign me? I am a GSSOC'22 participant.
Kindly assign me this issue.

**Comment by mar-galho** [comment]
@Krish2208 and @Himanshu1808, please check #4. 

We can dismember #4 into different issues. If you are interested in working on it, please go there and comment, so that we can do the necessary changes. I will close this discussion here.
