### ISSUE TITLE
Add PR and Issue template

### ISSUE THREAD

**Issue by mar-galho** [VishalSinghParmar2001/Relating-Social-Media-to-Stock-Movement-Public#5]
This is a simple task, but necessary: 

- [ ] Adding PR template
- [ ] Adding Issue template

Feel free to comment if you want to tackle this one.

**Comment by maityamit** [comment]
@ricardoprins 
I would like to work in this project under gssoc'22 
Please assign me . 

**Template Types**

![156198784-b2e8d551-3df4-4aff-a7c7-051a88c344c0](https://user-images.githubusercontent.com/74618071/156574710-6e75dbde-7ee9-4cb7-9297-c516d5092eb8.png)
![156169861-53b91128-a1aa-4751-805e-affb8a4924a3](https://user-images.githubusercontent.com/74618071/156574718-869a8c87-a672-4d4a-a32e-61e60fb0c6bc.png)

**Comment by mar-galho** [comment]
Done. Please go ahead - thanks for your disposition to work on this issue.
